### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by AndersBennedsgaard** [trifork/cheetah-feedback#13]
It should be as quick and easy as possible to leave our feedback.

Therefore, we should make use of [github issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).
(useful information [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository))

We should probably have separate templates for code bugs, feature requests, security issues, etc. 
The templates should be as simple as possible to follow.

An example of a bug template (placed in `.github/ISSUE_TEMPLATE/bug.yaml`):

```yaml
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["trifork/48"]
assignees:
  - trifork/cheetah-core-team
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: What area does the problem affect?
      multiple: true
      options:
        - Local development
        - Deploy to cluster
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
```
